"""add status

Revision ID: 312c56533850
Revises: 8056cb2d218d
Create Date: 2021-01-11 16:50:31.451623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '312c56533850'
down_revision = '8056cb2d218d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto', sa.Column('status', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auto', 'status')
    # ### end Alembic commands ###
