"""del Img

Revision ID: 8056cb2d218d
Revises: 079723cf350e
Create Date: 2021-01-11 00:29:37.323225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8056cb2d218d'
down_revision = '079723cf350e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('img')
    op.add_column('auto', sa.Column('img_id1', sa.String(length=128), nullable=True))
    op.add_column('auto', sa.Column('img_id2', sa.String(length=128), nullable=True))
    op.add_column('auto', sa.Column('img_id3', sa.String(length=128), nullable=True))
    op.add_column('auto', sa.Column('img_id4', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auto', 'img_id4')
    op.drop_column('auto', 'img_id3')
    op.drop_column('auto', 'img_id2')
    op.drop_column('auto', 'img_id1')
    op.create_table('img',
    sa.Column('img_id', sa.INTEGER(), nullable=False),
    sa.Column('auto_id', sa.INTEGER(), nullable=True),
    sa.Column('img_url', sa.VARCHAR(length=128), nullable=True),
    sa.ForeignKeyConstraint(['auto_id'], ['auto.id'], ),
    sa.PrimaryKeyConstraint('img_id')
    )
    # ### end Alembic commands ###
