"""add Jornal

Revision ID: abb6f287ed20
Revises: 312c56533850
Create Date: 2021-01-21 04:47:26.028968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abb6f287ed20'
down_revision = '312c56533850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jornal',
    sa.Column('rent_id', sa.Integer(), nullable=False),
    sa.Column('auto_id', sa.Integer(), nullable=True),
    sa.Column('rent_start', sa.DateTime(), nullable=True),
    sa.Column('rent_end', sa.DateTime(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['auto_id'], ['auto.id'], ),
    sa.PrimaryKeyConstraint('rent_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jornal')
    # ### end Alembic commands ###
